# Команды:
# /money help - помощь по командам.

# Права:
# money.admin - доступ к админской команде /money.
# money.[сумма] - множитель получения валюты раз в определенное время.

multiply: # настройка множителя
  amount: 100 # сумма выдачи
  time: 5 # время выдачи множителя в минутах

currency: # настройка валюты
  single: 'KK' # обозначение 1 валюты
  multiple: 'KK' # обозначение множества валюты